### ISSUE TITLE
Densitiy Setting

### ISSUE THREAD

**Issue by MichK-tech** [SunnySummit/LasagnaBiomeGeneration2#1]
Hi, 

your mod seams perfect in sight of variation, but I need to reduce overall density - but keep view distance and lod. Which file I have to choose for reducing only big objects density  and keep the rest in place?

**Comment by SunnySummit** [comment]
Glad you like overall variation. Obvious suggestion is to install Spawner_Minima and non-XL versions of paks. Otherwise, you can try modifying Env & CustomBiomes via. [Plumgen](https://github.com/SunnySummit/PLUMGEN). Lastly, a reminder that this mod is provided "as is."
