### ISSUE TITLE
Will you update it? 

### ISSUE THREAD

**Issue by Federicox92** [SunnySummit/LasagnaBiomeGeneration2#2]
Hi, will you update it, With new things?

**Comment by SunnySummit** [comment]
I might, I might not. For now, I'm interested in other modding ideas and games. That said, if the mod is broken please lmk.

You can always use [https://github.com/SunnySummit/PLUMGEN](https://github.com/SunnySummit/PLUMGEN) to make your own changes and even release it. Just be sure to follow the 5 "rules" found on the main page.

**Comment by SunnySummit** [comment]
I might, I might not. For now, I'm interested in other modding ideas and games. That said, if the mod is broken please lmk.

You can always use [https://github.com/SunnySummit/PLUMGEN](https://github.com/SunnySummit/PLUMGEN) to make your own changes and even release it. Just be sure to follow the 5 "rules" found on the main Lasagna page.

**Comment by SunnySummit** [comment]
I might, I might not. For now, I'm interested in other modding ideas. If the mod is broken please lmk.

Can always try [https://github.com/SunnySummit/PLUMGEN](https://github.com/SunnySummit/PLUMGEN) to make your own changes and distribute them. Be sure to follow the 5 "rules" found on main Lasagna page.
